# Generated by Django 5.1.2 on 2024-10-14 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photographers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photographer',
            name='cover_image',
            field=models.ImageField(default='cover_images/default_cover_image.jpg', upload_to='cover_images/'),
        ),
        migrations.AlterField(
            model_name='photographer',
            name='profile_image',
            field=models.ImageField(default='images/default_profile_image.jpg', upload_to='images/'),
        ),
    ]
