# Generated by Django 5.1.1 on 2024-09-24 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photographers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photographer',
            name='profile_image',
            field=models.ImageField(default='../zjadqskisbjlyfb5jb8i', upload_to='images/'),
        ),
    ]
