# Generated by Django 5.1.2 on 2024-10-12 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photographers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photographer',
            name='cover_image',
            field=models.ImageField(default='https://res.cloudinary.com/dwgtce0rh/image/upload/v1728754586/yf3ss5ywaxijslaanqqs.jpg', upload_to='cover_images/'),
        ),
        migrations.AlterField(
            model_name='photographer',
            name='profile_image',
            field=models.ImageField(default='https://res.cloudinary.com/dwgtce0rh/image/upload/v1728754586/yf3ss5ywaxijslaanqqs.jpg', upload_to='images/'),
        ),
    ]
