# Generated by Django 5.1.2 on 2024-10-14 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photographers', '0003_alter_photographer_cover_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photographer',
            name='cover_image',
            field=models.ImageField(default='cover_images/northumberlandcastle.jpg', upload_to='cover_images/'),
        ),
        migrations.AlterField(
            model_name='photographer',
            name='profile_image',
            field=models.ImageField(default='images/raceday.jpg', upload_to='images/'),
        ),
    ]
