# Generated by Django 5.1.1 on 2024-09-27 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photographers', '0003_follow'),
    ]

    operations = [
        migrations.AddField(
            model_name='photographer',
            name='follower_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='photographer',
            name='total_likes',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
