# Generated by Django 4.2 on 2024-12-02 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photographers', '0005_alter_photographer_cover_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='photographer',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, unique=True),
        ),
    ]
