# Generated by Django 5.1.3 on 2024-12-10 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photographers', '0005_alter_photographer_cover_image_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='follow',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='follow',
            constraint=models.UniqueConstraint(
                fields=('follower', 'following'), name='unique_follow'),
        ),
    ]
