# Generated by Django 5.1.1 on 2024-10-05 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photographers', '0005_alter_photographer_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photographer',
            name='cover_image',
            field=models.ImageField(default='../24633_a5n9zu', upload_to='cover_images/'),
        ),
        migrations.AlterField(
            model_name='photographer',
            name='profile_image',
            field=models.ImageField(default='../24633_a5n9zu', upload_to='images/'),
        ),
    ]
