# Generated by Django 5.1.3 on 2024-12-10 23:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photographers', '0006_alter_follow_unique_together_follow_unique_follow'),
        ('photographers', '0006_photographer_slug'),
    ]

    operations = [
    ]
