# Generated by Django 5.1.3 on 2024-12-10 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photographers', '0007_merge_20241210_2332'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='follow',
            name='unique_follow',
        ),
        migrations.AlterField(
            model_name='photographer',
            name='cover_image',
            field=models.ImageField(default='https://res.cloudinary.com/dwgtce0rh/image/upload/v1732845896/zhmwexi1zadfypgnolok.jpg', upload_to='cover_images/'),
        ),
        migrations.AlterField(
            model_name='photographer',
            name='profile_image',
            field=models.ImageField(default='https://res.cloudinary.com/dwgtce0rh/image/upload/v1732845896/zhmwexi1zadfypgnolok.jpg', upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='photographer',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='follow',
            unique_together={('follower', 'following')},
        ),
    ]
