# Generated by Django 4.2.7 on 2024-12-13 14:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photographers', '0009_alter_photographer_cover_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photographer',
            name='slug',
        ),
    ]
