# Generated by Django 4.2.7 on 2024-12-13 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photographers', '0014_remove_photographer_cover_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='photographer',
            name='cover_image',
            field=models.ImageField(default='../cs99p88tqdy3vf87cikh', upload_to='images/'),
        ),
    ]
