# Generated by Django 5.1.1 on 2024-09-27 08:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0001_initial'),
        ('photographers', '0002_alter_photographer_profile_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tag',
            options={'ordering': ['name']},
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('photo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='photo.photo')),
                ('photographer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='photographers.photographer')),
            ],
            options={
                'unique_together': {('photographer', 'photo')},
            },
        ),
    ]
