# Generated by Django 5.1.1 on 2024-09-27 09:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0002_alter_tag_options_like'),
        ('photographers', '0002_alter_photographer_profile_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('photo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='photo.photo')),
                ('photographer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='photographers.photographer')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('photographer', 'photo', 'content')},
            },
        ),
    ]
