# Generated by Django 5.1.1 on 2024-09-27 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0003_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='rating',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=3),
        ),
        migrations.AddField(
            model_name='photo',
            name='rating_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
