# Generated by Django 4.2 on 2024-11-28 11:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('photographers', '0003_alter_photographer_cover_image_and_more'),
        ('photo', '0003_alter_photo_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='photographer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                    related_name='photos', to='photographers.photographer'),
        ),
    ]
