# Generated by Django 5.1.2 on 2024-10-14 04:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0005_photo_likes_count_alter_photo_image'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='comment',
            name='unique_user_photo_content',
        ),
    ]
