# Generated by Django 5.1.2 on 2024-10-14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0005_photo_likes_count_alter_photo_image'),
    ]

    operations = [
        migrations.RunSQL(
            """
            -- Safely remove constraints from the 'photo_comment' model
            DO $$ 
            BEGIN
                IF EXISTS (SELECT conname FROM pg_constraint WHERE conname = 'unique_user_photo_content') THEN
                    ALTER TABLE photo_comment DROP CONSTRAINT unique_user_photo_content;
                END IF;
            END $$;

            -- Safely remove constraints from the 'photo_like' model
            DO $$ 
            BEGIN
                IF EXISTS (SELECT conname FROM pg_constraint WHERE conname = 'unique_user_photo_like') THEN
                    ALTER TABLE photo_like DROP CONSTRAINT unique_user_photo_like;
                END IF;
            END $$;

            -- Safely remove constraints from the 'photo_photorating' model
            DO $$ 
            BEGIN
                IF EXISTS (SELECT conname FROM pg_constraint WHERE conname = 'unique_user_photo_rating') THEN
                    ALTER TABLE photo_photorating DROP CONSTRAINT unique_user_photo_rating;
                END IF;
            END $$;
            """,
            reverse_sql="""
            -- Add back constraints (optional)
            ALTER TABLE photo_comment ADD CONSTRAINT unique_user_photo_content UNIQUE (user_id, photo_id, content);
            ALTER TABLE photo_like ADD CONSTRAINT unique_user_photo_like UNIQUE (user_id, photo_id);
            ALTER TABLE photo_photorating ADD CONSTRAINT unique_user_photo_rating UNIQUE (user_id, photo_id);
            """
        ),
    ]
