# Generated by Django 5.1.2 on 2024-10-14 04:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0006_remove_comment_unique_user_photo_content_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='comment',
            name='unique_user_photo_content',
        ),
        migrations.RemoveConstraint(
            model_name='like',
            name='unique_user_photo_like',
        ),
        migrations.RemoveConstraint(
            model_name='photorating',
            name='unique_user_photo_rating',
        ),
    ]
